From node:alpine as builder

WORKDIR '/app'

COPY package.json .
run npm install

copy . .
cmd npm run build

cmd ls -la

From nginx
cmd ls -la

COPY --from=builder /app/build/ /usr/share/nginx/html/
